version: "3.8"

services:
  web:
    build: .
    command: ./entrypoint.sh
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/assets

volumes:
  static_volume: {}
