# Generated by Django 5.1.4 on 2025-01-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_categorybudget_monthlyincome_monthlysavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybudget',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
